### ISSUE TITLE
GET    /authors/:id not functioning

### ISSUE THREAD

**Issue by jamesee** [jakecoffman/gorest#1]
Hi,

I tested your codes and found that the "GET    /authors/:id" not working.
The result var is not assigned and the return httpstatus is alway 500 [see controller.go line 73~78]
I do not know how to change your code.

Please note.

James

**Comment by jamesee** [comment]
Do you have a youtube tutorial to explain your codes? 
I would like to learn the way you write your codes.

**Comment by jakecoffman** [comment]
I fixed it, thanks for finding that.

Since this project uses reflection to reduce boilerplate it can be hard to read. Try searching for reflection tutorials.

Once generics are available I'll probably write this again using generics and I suspect it will be more clear.

**Comment by jamesee** [comment]
Many thanks for the quick update and pointing me to read up on reflection.

Quite a steep learning curve for me. :)

James
